#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Exploretum.Resource", IsApplication=true)]

namespace Exploretum
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int leopard_moth_sprite = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int magnolia_sprite = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pink_flowers = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int button1 = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int buttonBack = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int buttonMain = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int buttonNextQuest = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int buttonStart = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int distance = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int hotcold = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int latitude = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int longitude = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int provider = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int questName = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int queststory = 2131099656;
			
			// aapt resource value: 0x7f06000e
			public const int sprite = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int thanks = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CompleteQuest = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int End = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Map = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Quest = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int pink_flowers = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int latitude_string = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int longitude_string = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int provider_string = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
